name: Pull Request Check Workflow
on:
  workflow_call:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5
        id: commitlint-github-action
        with:
          failOnWarnings: false
          helpURL: https://adup-tech.atlassian.net/wiki/spaces/UA/pages/3509190661/Git+Commit+Message+Convention
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment PR
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            :robot: commit linter results for:
            ${{ toJSON(steps.commitlint-github-action.outputs.results).message }}

            :no_entry: erros:
            > ${{ join(toJSON(steps.commitlint-github-action.outputs.results).errors, '<br>') }}

            :warning: warnings:
            > ${{ join(toJSON(steps.commitlint-github-action.outputs.results).warnings, '<br>') }}

            Please fix it!
            see: [Commit message conventions](https://adup-tech.atlassian.net/wiki/spaces/UA/pages/3509190661/Git+Commit+Message+Convention)
          reactions: eyes
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}